packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  graphql-hooks@*:
    dependencies:
      react: "link:./preact-compat.js"
      react-dom: "link:./preact-compat.js"
  linaria@*:
    dependencies:
      react: "link:./preact-compat.js"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
