plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  "@apollo/client@3.1.3":
    dependencies:
      react-dom: "16.13.1"
  "@apollographql/apollo-tools@0.4.8":
    dependencies:
      graphql: "14.7.0"
  "styled-components@5.1.1":
    dependencies:
      react-is: 16.13.1
