AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Page service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PageServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/
      Handler: handler.page
      Runtime: nodejs12.x
      Events:
        PageService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /page
            Method: get
      Environment:
        Variables:
          DATA_SERVICE: ""
          WEBPACK_BUNDLE_SERVER: ""

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PageServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for Page Service function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/data/"
  PageServiceFunction:
    Description: "Page Service Lambda Function ARN"
    Value: !GetAtt PageServiceFunction.Arn
  PageServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Page Service function"
    Value: !GetAtt PageServiceFunctionRole.Arn
